"""initial schema

Revision ID: 57c313935953
Revises: 
Create Date: 2026-04-27 16:59:49.357295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57c313935953'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecole_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_number', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title_fr', sa.String(length=200), nullable=True),
    sa.Column('title_en', sa.String(length=200), nullable=True),
    sa.Column('title_es', sa.String(length=200), nullable=True),
    sa.Column('short_description_fr', sa.Text(), nullable=True),
    sa.Column('short_description_en', sa.Text(), nullable=True),
    sa.Column('short_description_es', sa.Text(), nullable=True),
    sa.Column('detailed_content_fr', sa.Text(), nullable=True),
    sa.Column('detailed_content_en', sa.Text(), nullable=True),
    sa.Column('detailed_content_es', sa.Text(), nullable=True),
    sa.Column('prerequisite_lesson_number', sa.Integer(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('phase', sa.Integer(), nullable=True),
    sa.Column('subline_en', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecole_lessons_code'), 'ecole_lessons', ['code'], unique=True)
    op.create_index(op.f('ix_ecole_lessons_id'), 'ecole_lessons', ['id'], unique=False)
    op.create_index(op.f('ix_ecole_lessons_lesson_number'), 'ecole_lessons', ['lesson_number'], unique=True)
    op.create_table('tache1_openings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opening_prompt_fr', sa.Text(), nullable=False),
    sa.Column('opening_prompt_en', sa.Text(), nullable=True),
    sa.Column('opening_prompt_es', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tache1_openings_id'), 'tache1_openings', ['id'], unique=False)
    op.create_table('tache2_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('title_fr', sa.String(length=200), nullable=True),
    sa.Column('title_en', sa.String(length=200), nullable=True),
    sa.Column('title_es', sa.String(length=200), nullable=True),
    sa.Column('candidate_brief_fr', sa.Text(), nullable=True),
    sa.Column('candidate_brief_en', sa.Text(), nullable=True),
    sa.Column('candidate_brief_es', sa.Text(), nullable=True),
    sa.Column('examiner_persona', sa.Text(), nullable=True),
    sa.Column('data_targets', sa.Text(), nullable=True),
    sa.Column('register', sa.String(length=20), nullable=True),
    sa.Column('difficulty', sa.String(length=10), nullable=True),
    sa.Column('seeded_from', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tache2_scenarios_code'), 'tache2_scenarios', ['code'], unique=True)
    op.create_index(op.f('ix_tache2_scenarios_id'), 'tache2_scenarios', ['id'], unique=False)
    op.create_table('test_topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('theme', sa.String(length=100), nullable=True),
    sa.Column('sous_theme', sa.String(length=200), nullable=True),
    sa.Column('tache_3_prompt_fr', sa.Text(), nullable=True),
    sa.Column('tache_3_prompt_en', sa.Text(), nullable=True),
    sa.Column('tache_3_prompt_es', sa.Text(), nullable=True),
    sa.Column('tache_3_difficulty', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_topics_id'), 'test_topics', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('ui_language', sa.String(length=5), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('target_level', sa.String(length=10), nullable=True),
    sa.Column('exam_profile', sa.String(length=50), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('goal', sa.String(length=100), nullable=True),
    sa.Column('current_level', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('writing_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('theme', sa.String(length=100), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('prompt_type', sa.String(length=50), nullable=False),
    sa.Column('min_words', sa.Integer(), nullable=True),
    sa.Column('max_words', sa.Integer(), nullable=True),
    sa.Column('time_limit_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_prompts_id'), 'writing_prompts', ['id'], unique=False)
    op.create_table('ecole_quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.String(length=32), nullable=False),
    sa.Column('question_fr', sa.Text(), nullable=True),
    sa.Column('question_en', sa.Text(), nullable=True),
    sa.Column('question_es', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('accepted_alternatives', sa.Text(), nullable=True),
    sa.Column('explanation_fr', sa.Text(), nullable=True),
    sa.Column('explanation_en', sa.Text(), nullable=True),
    sa.Column('explanation_es', sa.Text(), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['ecole_lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ecole_quiz_questions_id'), 'ecole_quiz_questions', ['id'], unique=False)
    op.create_index(op.f('ix_ecole_quiz_questions_lesson_id'), 'ecole_quiz_questions', ['lesson_id'], unique=False)
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('target_level', sa.String(length=10), nullable=True),
    sa.Column('audio_path', sa.String(length=500), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('stt_confidence', sa.Float(), nullable=True),
    sa.Column('low_confidence_words', sa.Text(), nullable=True),
    sa.Column('argument_structure', sa.Text(), nullable=True),
    sa.Column('corrected_transcript', sa.Text(), nullable=True),
    sa.Column('transcript_confirmed', sa.Boolean(), nullable=True),
    sa.Column('fluency', sa.Text(), nullable=True),
    sa.Column('tache_mode', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['test_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recordings_id'), 'recordings', ['id'], unique=False)
    op.create_table('remediation_modules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name_fr', sa.String(length=200), nullable=False),
    sa.Column('name_en', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('L1_interference_description_fr', sa.Text(), nullable=False),
    sa.Column('L1_interference_description_en', sa.Text(), nullable=False),
    sa.Column('detection_criteria', sa.Text(), nullable=False),
    sa.Column('examples', sa.Text(), nullable=False),
    sa.Column('content_refs', sa.Text(), nullable=False),
    sa.Column('drill_ids', sa.Text(), nullable=False),
    sa.Column('prerequisite_module_ids', sa.Text(), nullable=False),
    sa.Column('ecole_lesson_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ecole_lesson_id'], ['ecole_lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_modules_id'), 'remediation_modules', ['id'], unique=False)
    op.create_table('user_ecole_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('quiz_attempts', sa.Integer(), nullable=True),
    sa.Column('quiz_best_score', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['ecole_lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_user_lesson')
    )
    op.create_index(op.f('ix_user_ecole_progress_id'), 'user_ecole_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_ecole_progress_lesson_id'), 'user_ecole_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_user_ecole_progress_user_id'), 'user_ecole_progress', ['user_id'], unique=False)
    op.create_table('writing_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('prompt_id', sa.Integer(), nullable=False),
    sa.Column('student_text', sa.Text(), nullable=False),
    sa.Column('feedback_json', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['writing_prompts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_submissions_id'), 'writing_submissions', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tache_mode', sa.String(length=20), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('target_level', sa.String(length=10), nullable=True),
    sa.Column('ui_language', sa.String(length=5), nullable=True),
    sa.Column('exam_profile', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('scenario_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['tache2_scenarios.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['test_topics.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('note_globale', sa.Float(), nullable=True),
    sa.Column('score_le_fond', sa.Float(), nullable=True),
    sa.Column('score_les_moules_des_idees', sa.Float(), nullable=True),
    sa.Column('score_les_moules', sa.Float(), nullable=True),
    sa.Column('score_les_reflexes_anglais', sa.Float(), nullable=True),
    sa.Column('score_prononciation', sa.Float(), nullable=True),
    sa.Column('prononciation_data', sa.Text(), nullable=True),
    sa.Column('goulet_couche', sa.Integer(), nullable=True),
    sa.Column('goulet_nom', sa.String(length=50), nullable=True),
    sa.Column('goulet_explication', sa.Text(), nullable=True),
    sa.Column('ce_qui_marche', sa.Text(), nullable=True),
    sa.Column('analyse_le_fond', sa.Text(), nullable=True),
    sa.Column('analyse_les_moules_des_idees', sa.Text(), nullable=True),
    sa.Column('analyse_les_moules', sa.Text(), nullable=True),
    sa.Column('analyse_les_reflexes_anglais', sa.Text(), nullable=True),
    sa.Column('la_prochaine_etape', sa.Text(), nullable=True),
    sa.Column('transcription_corrigee', sa.Text(), nullable=True),
    sa.Column('patterns_detectes', sa.Text(), nullable=True),
    sa.Column('patterns_manquants', sa.Text(), nullable=True),
    sa.Column('reflexes_detectes', sa.Text(), nullable=True),
    sa.Column('corrections', sa.Text(), nullable=True),
    sa.Column('ordonnance', sa.Text(), nullable=True),
    sa.Column('raw_llm_response', sa.Text(), nullable=True),
    sa.Column('criteria_breakdown', sa.Text(), nullable=True),
    sa.Column('cefr_level', sa.String(length=20), nullable=True),
    sa.Column('clb_level', sa.Integer(), nullable=True),
    sa.Column('exam_profile', sa.String(length=50), nullable=True),
    sa.Column('examiner_remarks', sa.Text(), nullable=True),
    sa.Column('teacher_coaching', sa.Text(), nullable=True),
    sa.Column('feedback_grid', sa.Text(), nullable=True),
    sa.Column('tache_rubric_data', sa.Text(), nullable=True),
    sa.Column('narrative_summary', sa.Text(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('analysis_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_id'), 'feedbacks', ['id'], unique=False)
    op.create_table('session_detected_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('supporting_quote', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['remediation_modules.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_detected_modules_id'), 'session_detected_modules', ['id'], unique=False)
    op.create_index(op.f('ix_session_detected_modules_module_id'), 'session_detected_modules', ['module_id'], unique=False)
    op.create_index(op.f('ix_session_detected_modules_recording_id'), 'session_detected_modules', ['recording_id'], unique=False)
    op.create_table('conversation_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('stt_confidence', sa.Float(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('fluency', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_by_turn_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_turns_conversation_id'), 'conversation_turns', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_turns_id'), 'conversation_turns', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_turns_superseded_at'), 'conversation_turns', ['superseded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_turns_superseded_at'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_id'), table_name='conversation_turns')
    op.drop_index(op.f('ix_conversation_turns_conversation_id'), table_name='conversation_turns')
    op.drop_table('conversation_turns')
    op.drop_index(op.f('ix_session_detected_modules_recording_id'), table_name='session_detected_modules')
    op.drop_index(op.f('ix_session_detected_modules_module_id'), table_name='session_detected_modules')
    op.drop_index(op.f('ix_session_detected_modules_id'), table_name='session_detected_modules')
    op.drop_table('session_detected_modules')
    op.drop_index(op.f('ix_feedbacks_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_writing_submissions_id'), table_name='writing_submissions')
    op.drop_table('writing_submissions')
    op.drop_index(op.f('ix_user_ecole_progress_user_id'), table_name='user_ecole_progress')
    op.drop_index(op.f('ix_user_ecole_progress_lesson_id'), table_name='user_ecole_progress')
    op.drop_index(op.f('ix_user_ecole_progress_id'), table_name='user_ecole_progress')
    op.drop_table('user_ecole_progress')
    op.drop_index(op.f('ix_remediation_modules_id'), table_name='remediation_modules')
    op.drop_table('remediation_modules')
    op.drop_index(op.f('ix_recordings_id'), table_name='recordings')
    op.drop_table('recordings')
    op.drop_index(op.f('ix_ecole_quiz_questions_lesson_id'), table_name='ecole_quiz_questions')
    op.drop_index(op.f('ix_ecole_quiz_questions_id'), table_name='ecole_quiz_questions')
    op.drop_table('ecole_quiz_questions')
    op.drop_index(op.f('ix_writing_prompts_id'), table_name='writing_prompts')
    op.drop_table('writing_prompts')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_test_topics_id'), table_name='test_topics')
    op.drop_table('test_topics')
    op.drop_index(op.f('ix_tache2_scenarios_id'), table_name='tache2_scenarios')
    op.drop_index(op.f('ix_tache2_scenarios_code'), table_name='tache2_scenarios')
    op.drop_table('tache2_scenarios')
    op.drop_index(op.f('ix_tache1_openings_id'), table_name='tache1_openings')
    op.drop_table('tache1_openings')
    op.drop_index(op.f('ix_ecole_lessons_lesson_number'), table_name='ecole_lessons')
    op.drop_index(op.f('ix_ecole_lessons_id'), table_name='ecole_lessons')
    op.drop_index(op.f('ix_ecole_lessons_code'), table_name='ecole_lessons')
    op.drop_table('ecole_lessons')
    # ### end Alembic commands ###
