"""F-320 smoke — Le Vocabulaire DB schema verification.

Run with: python -m scripts.smoke_f320
Expected: prints PASS lines and exits 0. Cleans up its own test rows.

Verifies:
  1. All 5 new tables exist.
  2. CHECK constraints enforce on all 4 enum columns
     (corpus_partition, source_type, register, exam_tag), including
     rejection of the legacy stale `oqlf` source_type from the
     superseded BACKLOG.md text.
  3. UNIQUE constraints enforce on all 4 unique pairs/columns
     (slug, list name per user, list_chunk pair, progress pair).
  4. CASCADE FK behavior: deleting a user reclaims their lists and
     progress rows; deleting a chunk reclaims its list-membership and
     progress rows.
  5. All declared indices are present in pg_indexes (12 named indices
     across 5 tables; PK index is auto-generated by Postgres and not
     enumerated).
  6. ORM round-trip across all 5 models (insert + query + relationship
     navigation).

No reliance on the migration revision being `head` — the smoke runs
against whatever's deployed and is idempotent (each fixture is
prefixed `smoke_f320_` and the cleanup step removes them).
"""
from __future__ import annotations

import datetime
import sys

from sqlalchemy import create_engine, text
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from app.models.models import User
from app.models.vocabulaire import (
    UserVocabList,
    UserVocabListChunk,
    UserVocabProgress,
    VocabChunk,
    VocabTopic,
)


engine = create_engine(
    "postgresql+psycopg://fluentpath:fluentpath_local_dev@localhost:5432/fluentpath"
)

errors: list[str] = []


def check(name: str, ok: bool, detail: str = "") -> None:
    status = "PASS" if ok else "FAIL"
    extra = f" -- {detail}" if detail else ""
    print(f"  [{status}] {name}{extra}")
    if not ok:
        errors.append(name)


def main() -> int:
    print("Step 1: 5 new tables exist")
    expected_tables = {
        "vocab_topics",
        "vocab_chunks",
        "user_vocab_lists",
        "user_vocab_list_chunks",
        "user_vocab_progress",
    }
    with engine.connect() as c:
        rows = c.execute(
            text(
                "SELECT table_name FROM information_schema.tables "
                "WHERE table_schema='public' AND table_name = ANY(:t)"
            ),
            {"t": list(expected_tables)},
        ).fetchall()
    found_tables = {r[0] for r in rows}
    check(
        "5 tables present",
        found_tables == expected_tables,
        f"missing: {expected_tables - found_tables}"
        if expected_tables - found_tables
        else "all 5",
    )

    print("\nStep 2: 16 named indices exist")
    expected_indices = {
        # vocab_topics
        "ix_vocab_topics_id",
        "ix_vocab_topics_slug",
        "ix_vocab_topics_corpus_partition",
        # vocab_chunks
        "ix_vocab_chunks_id",
        "ix_vocab_chunks_topic_id",
        "ix_vocab_chunks_exam_tag",
        "ix_vocab_chunks_topic_level",
        # user_vocab_lists
        "ix_user_vocab_lists_id",
        "ix_user_vocab_lists_user_id",
        "ix_user_vocab_lists_user_created",
        # user_vocab_list_chunks
        "ix_user_vocab_list_chunks_id",
        "ix_user_vocab_list_chunks_list_id",
        "ix_user_vocab_list_chunks_chunk",
        # user_vocab_progress
        "ix_user_vocab_progress_id",
        "ix_user_vocab_progress_user_id",
        "ix_user_vocab_progress_user_lastseen",
    }
    with engine.connect() as c:
        idx_rows = c.execute(
            text(
                "SELECT indexname FROM pg_indexes "
                "WHERE schemaname='public' AND indexname = ANY(:i)"
            ),
            {"i": list(expected_indices)},
        ).fetchall()
    found_indices = {r[0] for r in idx_rows}
    check(
        f"{len(expected_indices)} indices present",
        found_indices == expected_indices,
        f"missing: {expected_indices - found_indices}"
        if expected_indices - found_indices
        else "all present",
    )

    print("\nSetup: fixture user")
    with Session(engine) as s:
        u = s.query(User).filter_by(email="smoke@f320.local").first()
        if not u:
            u = User(
                email="smoke@f320.local",
                hashed_password="x",
                full_name="F-320 Smoke",
            )
            s.add(u)
            s.commit()
            s.refresh(u)
        user_id = u.id
    print(f"  user_id={user_id}")

    print("\nStep 3: ORM round-trip -- VocabTopic")
    with Session(engine) as s:
        topic = VocabTopic(
            slug="smoke_f320_tcf_tourism",
            labels={"fr": "Tourisme", "en": "Tourism", "es": "Turismo"},
            description={"fr": "Vocabulaire des voyages", "en": "Travel vocab"},
            corpus_partition="exam_tagged_TCF",
            cefr_level_min="A2",
            cefr_level_max="B2",
        )
        s.add(topic)
        s.commit()
        s.refresh(topic)
        topic_id = topic.id

        free_topic = VocabTopic(
            slug="smoke_f320_general_loisirs",
            labels={"fr": "Loisirs"},
            corpus_partition="free_general",
        )
        s.add(free_topic)
        s.commit()
        s.refresh(free_topic)
        free_topic_id = free_topic.id
    check("VocabTopic insert + readback", topic_id is not None and free_topic_id is not None)

    print("\nStep 4: ORM round-trip -- VocabChunk across all 4 source_type enums")
    with Session(engine) as s:
        chunks_by_source = {
            "CC_corpus": VocabChunk(
                chunk_fr="faire ses bagages",
                chunk_en="to pack one's bags",
                topic_id=topic_id,
                source="https://fr.wiktionary.org/wiki/faire_ses_bagages",
                source_type="CC_corpus",
                register="formel",
                exam_tag="tcf",
                cefr_level="B1",
            ),
            "chadi_authored": VocabChunk(
                chunk_fr="prendre son envol",
                chunk_en="to take off",
                topic_id=topic_id,
                source="andre-course-notes-2024-03.docx",
                source_type="chadi_authored",
                register="semi_formel",
                exam_tag="tcf",
                cefr_level="B2",
            ),
            "book_lab": VocabChunk(
                chunk_fr="un voyage à l'étranger",
                chunk_en="a trip abroad",
                topic_id=topic_id,
                source="book-lab-travel-vocab-volume-1",
                source_type="book_lab",
                register="informel",
                exam_tag="delf",
                cefr_level="B1",
            ),
            "third_party_publisher": VocabChunk(
                chunk_fr="croque-monsieur",
                topic_id=topic_id,
                source="Vocabulaire Progressif du Français B1",
                source_type="third_party_publisher_DO_NOT_EXTRACT",
                cefr_level="B1",
            ),
        }
        for chunk in chunks_by_source.values():
            s.add(chunk)
        s.commit()
        chunk_ids = {k: c.id for k, c in chunks_by_source.items()}
    check(
        "4 chunks (one per source_type enum) inserted",
        all(cid is not None for cid in chunk_ids.values()),
        f"ids: {chunk_ids}",
    )

    print("\nStep 5: ORM round-trip -- UserVocabList + UserVocabListChunk + UserVocabProgress")
    with Session(engine) as s:
        vlist = UserVocabList(user_id=user_id, name="Smoke Test List")
        s.add(vlist)
        s.commit()
        s.refresh(vlist)
        list_id = vlist.id

        membership = UserVocabListChunk(
            list_id=list_id, chunk_id=chunk_ids["CC_corpus"]
        )
        s.add(membership)
        progress = UserVocabProgress(
            user_id=user_id,
            chunk_id=chunk_ids["CC_corpus"],
            seen_count=3,
            correct_count=2,
            last_seen_at=datetime.datetime.utcnow(),
        )
        s.add(progress)
        s.commit()

        # Relationship navigation
        fresh = s.get(UserVocabList, list_id)
        rt_ok = (
            len(fresh.chunks) == 1
            and fresh.chunks[0].chunk.chunk_fr == "faire ses bagages"
        )
    check("List -> chunks -> chunk round-trip", rt_ok)

    print("\nStep 6: CHECK ck_vocab_topics_corpus_partition rejects bad value")
    with Session(engine) as s:
        bad = VocabTopic(
            slug="smoke_f320_bad_partition",
            corpus_partition="exam_tagged_SAT",
        )
        s.add(bad)
        try:
            s.commit()
            check("bad corpus_partition rejected", False, "INSERT succeeded")
        except IntegrityError:
            check("bad corpus_partition rejected", True)
            s.rollback()

    print("\nStep 7: CHECK ck_vocab_chunks_source_type rejects legacy 'oqlf' enum")
    with Session(engine) as s:
        bad = VocabChunk(
            chunk_fr="x",
            topic_id=topic_id,
            source_type="oqlf",
        )
        s.add(bad)
        try:
            s.commit()
            check(
                "legacy 'oqlf' source_type rejected (D2 enum lock-in)",
                False,
                "INSERT succeeded — stale enum is still accepted",
            )
        except IntegrityError:
            check(
                "legacy 'oqlf' source_type rejected (D2 enum lock-in)", True
            )
            s.rollback()

    print("\nStep 8: CHECK ck_vocab_chunks_register rejects bad register")
    with Session(engine) as s:
        bad = VocabChunk(
            chunk_fr="x",
            topic_id=topic_id,
            source_type="chadi_authored",
            register="vulgaire",
        )
        s.add(bad)
        try:
            s.commit()
            check("bad register rejected", False, "INSERT succeeded")
        except IntegrityError:
            check("bad register rejected", True)
            s.rollback()

    print("\nStep 9: CHECK ck_vocab_chunks_exam_tag rejects bad exam_tag")
    with Session(engine) as s:
        bad = VocabChunk(
            chunk_fr="x",
            topic_id=topic_id,
            source_type="chadi_authored",
            exam_tag="sat",
        )
        s.add(bad)
        try:
            s.commit()
            check("bad exam_tag rejected", False, "INSERT succeeded")
        except IntegrityError:
            check("bad exam_tag rejected", True)
            s.rollback()

    print("\nStep 10: UNIQUE uq_user_vocab_lists_user_name rejects duplicate name per user")
    with Session(engine) as s:
        dup = UserVocabList(user_id=user_id, name="Smoke Test List")
        s.add(dup)
        try:
            s.commit()
            check("duplicate list name per user rejected", False, "INSERT succeeded")
        except IntegrityError:
            check("duplicate list name per user rejected", True)
            s.rollback()

    print("\nStep 11: UNIQUE uq_user_vocab_list_chunks_list_chunk rejects dup membership")
    with Session(engine) as s:
        dup = UserVocabListChunk(
            list_id=list_id, chunk_id=chunk_ids["CC_corpus"]
        )
        s.add(dup)
        try:
            s.commit()
            check("duplicate chunk-in-list rejected", False, "INSERT succeeded")
        except IntegrityError:
            check("duplicate chunk-in-list rejected", True)
            s.rollback()

    print("\nStep 12: UNIQUE uq_user_vocab_progress_user_chunk rejects dup progress row")
    with Session(engine) as s:
        dup = UserVocabProgress(
            user_id=user_id, chunk_id=chunk_ids["CC_corpus"], seen_count=99
        )
        s.add(dup)
        try:
            s.commit()
            check("duplicate (user, chunk) progress row rejected", False, "INSERT succeeded")
        except IntegrityError:
            check("duplicate (user, chunk) progress row rejected", True)
            s.rollback()

    print("\nStep 13: index path -- topic-page query (topic_id, cefr_level)")
    with Session(engine) as s:
        rows = (
            s.query(VocabChunk)
            .filter(VocabChunk.topic_id == topic_id, VocabChunk.cefr_level == "B1")
            .all()
        )
    check(
        "composite (topic_id, cefr_level) prefix query returns expected count",
        len(rows) == 3,
        f"got {len(rows)} chunks at B1 (expected 3: CC_corpus + book_lab + third_party)",
    )

    print("\nStep 14: CASCADE chunk delete -- list-chunk membership goes with chunk")
    chunk_to_delete = chunk_ids["book_lab"]
    # Add a membership for this chunk first so we have something to CASCADE
    with Session(engine) as s:
        s.add(UserVocabListChunk(list_id=list_id, chunk_id=chunk_to_delete))
        s.commit()
    # Verify membership row exists pre-delete
    with engine.connect() as c:
        pre = c.execute(
            text(
                "SELECT count(*) FROM user_vocab_list_chunks WHERE chunk_id = :c"
            ),
            {"c": chunk_to_delete},
        ).scalar()
    # Delete chunk; CASCADE should reclaim the membership row
    with Session(engine) as s:
        s.query(VocabChunk).filter_by(id=chunk_to_delete).delete()
        s.commit()
    with engine.connect() as c:
        post = c.execute(
            text(
                "SELECT count(*) FROM user_vocab_list_chunks WHERE chunk_id = :c"
            ),
            {"c": chunk_to_delete},
        ).scalar()
    check(
        "CASCADE on chunk delete clears list-chunk membership",
        pre == 1 and post == 0,
        f"pre={pre} post={post}",
    )

    print("\nCleanup")
    with engine.connect() as c:
        c.execute(
            text(
                "DELETE FROM user_vocab_progress WHERE user_id = :u"
            ),
            {"u": user_id},
        )
        c.execute(
            text("DELETE FROM user_vocab_list_chunks WHERE list_id IN ("
                 "SELECT id FROM user_vocab_lists WHERE user_id = :u)"),
            {"u": user_id},
        )
        c.execute(
            text("DELETE FROM user_vocab_lists WHERE user_id = :u"),
            {"u": user_id},
        )
        c.execute(
            text(
                "DELETE FROM vocab_chunks WHERE topic_id IN ("
                "SELECT id FROM vocab_topics WHERE slug LIKE 'smoke_f320_%')"
            )
        )
        c.execute(
            text("DELETE FROM vocab_topics WHERE slug LIKE 'smoke_f320_%'")
        )
        c.execute(text("DELETE FROM users WHERE id = :u"), {"u": user_id})
        c.commit()
    print("  test rows removed")

    print()
    if errors:
        print(f"FAILURES: {errors}")
        return 1
    print("ALL CHECKS PASSED")
    return 0


if __name__ == "__main__":
    sys.exit(main())
